name: PHPStan

on:
  push:
    branches:
      - main
    paths:
      - '**.php'
      - 'phpstan.neon.dist'
      - 'composer.json'
  pull_request:
  workflow_dispatch:

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
          coverage: none
          extensions: gd, intl, mbstring, pdo_mysql, sodium, zip

      - name: Install dependencies
        run: composer update --no-ansi --no-interaction --no-progress

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --no-progress
